# Generated by Django 4.2.5 on 2024-02-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='conclusion',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
