# Generated by Django 5.2.5 on 2025-11-15 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_amount_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderupdate',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Order Update', 'verbose_name_plural': 'Order Updates'},
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(blank=True, help_text='Actual delivery date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Expected delivery date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(blank=True, help_text='Date when order was shipped', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Shipping tracking number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='is_customer_notified',
            field=models.BooleanField(default=False, help_text='Whether customer has been notified'),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='location',
            field=models.CharField(blank=True, help_text='Current location of shipment', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderupdate_set', to='shop.order'),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='status_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('payment_received', 'Payment Received'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('other', 'Other')], default='other', help_text='Type of status update', max_length=20),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking number if applicable', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cc', 'Credit/Debit Card'), ('upi', 'UPI Payment'), ('cod', 'Cash on Delivery')], default='cc', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cod_pending', 'COD Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
