# Generated by Django 5.2.5 on 2025-11-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_populate_order_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_json',
            field=models.CharField(default='{}', max_length=5000),
        ),
    ]
