# Generated by Django 4.2.5 on 2025-11-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_state_alter_order_item_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AlterField(
            model_name='order',
            name='item_json',
            field=models.CharField(max_length=5000),
        ),
    ]
