"""
Django settings for Ecommerceweb project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-is-o39*x_bxsy%*gk=b34j+r--z90c%hswc^=jq-msl4==i_=q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'shop.apps.ShopConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'account',
    'blog',
    
]

# JWT configuration 
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ) 
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ecommerceweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['Ecommerceweb/templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ecommerceweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = '/media/'

AUTH_USER_MODEL = 'account.User'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=20),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",


    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",

}

# Email configuration for OTP/MFA
# Set USE_CONSOLE_EMAIL=True to use console backend (emails print to terminal)
# Set USE_CONSOLE_EMAIL=False to use SMTP (emails sent to actual inbox)
# USE_CONSOLE_EMAIL = os.environ.get('USE_CONSOLE_EMAIL', 'False').lower() == 'true'

# Show OTP in UI as fallback when email fails (only in DEBUG mode)
SHOW_OTP_IN_UI_FALLBACK = DEBUG

IN_TESTS = 'test' in sys.argv
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'false').lower() == 'true'
# if USE_CONSOLE_EMAIL and not IN_TESTS:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#     DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Outfit Avenue <noreply@outfitavenue.com>')
# else:
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'Outfit Avenue <{EMAIL_HOST_USER}>')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Outfit Avenue <noreply@outfitavenue.com>')
    
    # ============================================================================
    # GMAIL APP PASSWORD SETUP - DETAILED INSTRUCTIONS
    # ============================================================================
    # For Gmail, you MUST use an App Password, NOT your regular Gmail password.
    # Regular passwords will NOT work and will show "BadCredentials" error.
    #
    # STEP-BY-STEP GUIDE:
    #
    # STEP 1: Go to Google Account Settings
    #   - Open your web browser
    #   - Go to: https://myaccount.google.com/
    #   - Sign in with your Gmail account (garmy564@gmail.com)
    #
    # STEP 2: Enable 2-Step Verification (REQUIRED - Cannot skip this step)
    #   - On the left sidebar, click "Security"
    #   - Scroll down to "How you sign in to Google"
    #   - Find "2-Step Verification" and click on it
    #   - If it's OFF, click "Get Started" to enable it
    #   - Follow the prompts to set up 2-Step Verification:
    #     * Enter your phone number
    #     * Verify with a code sent via SMS or phone call
    #     * Click "Turn On" to complete setup
    #   - IMPORTANT: You CANNOT create App Passwords without 2-Step Verification
    #
    # STEP 3: Create App Password
    #   - Still in Security settings, scroll down to "2-Step Verification"
    #   - Click on "App passwords" (this option only appears AFTER 2-Step is enabled)
    #   - You may need to sign in again for security
    #
    # STEP 4: Generate App Password
    #   - In the "App passwords" page:
    #     * Select "Mail" from the "Select app" dropdown
    #     * Select "Other (Custom name)" from "Select device" dropdown
    #     * Type "Django Ecommerce" or any name you prefer
    #     * Click "Generate" button
    #
    # STEP 5: Copy the App Password
    #   - Google will show you a 16-character password
    #   - It will look like: "abcd efgh ijkl mnop" (with spaces)
    #   - Click "Copy" or manually copy it
    #   - IMPORTANT: This password is shown ONLY ONCE - save it securely!
    #
    # STEP 6: Update This File
    #   - Paste the 16-character password below in EMAIL_HOST_PASSWORD
    #   - REMOVE ALL SPACES from the password
    #   - Example: If Google shows "abcd efgh ijkl mnop"
    #             Use: "abcdefghijklmnop" (no spaces)
    #
    # STEP 7: Save and Restart
    #   - Save this settings.py file
    #   - Restart your Django development server
    #   - Try registering/login again - emails should now send successfully
    #
    # TROUBLESHOOTING:
    #   - If "App passwords" option is missing: Enable 2-Step Verification first
    #   - If password doesn't work: Make sure you removed all spaces
    #   - If still failing: Generate a new App Password and try again
    #   - Check spam folder: Sometimes emails go to spam initially
    #
    # ALTERNATIVE: If you can't use App Passwords, the system will show OTP
    #              in the UI automatically when email fails (fallback feature)
    # ============================================================================

# Google OAuth2 Configuration
# ============================================================================
# GOOGLE OAUTH2 SETUP - DETAILED INSTRUCTIONS
# ============================================================================
# To enable Google login, you need to:
#
# STEP 1: Go to Google Cloud Console
#   - Open: https://console.cloud.google.com/
#   - Sign in with your Google account
#   - Create a new project or select an existing one
#
# STEP 2: Enable Google+ API
#   - Go to "APIs & Services" > "Library"
#   - Search for "Google+ API" and enable it
#   - Also enable "Google Identity" if available
#
# STEP 3: Create OAuth 2.0 Credentials
#   - Go to "APIs & Services" > "Credentials"
#   - Click "Create Credentials" > "OAuth client ID"
#   - If prompted, configure the OAuth consent screen first:
#     * Choose "External" (unless you have a Google Workspace)
#     * Fill in app name: "Outfit Avenue"
#     * Add your email as support email
#     * Add scopes: email, profile, openid
#     * Add test users if in testing mode
#
# STEP 4: Create OAuth Client ID
#   - Application type: "Web application"
#   - Name: "Outfit Avenue Web Client"
#   - Authorized redirect URIs:
#     * For development: http://127.0.0.1:8000/account/social/google/callback/
#     * For production: https://yourdomain.com/account/social/google/callback/
#   - Click "Create"
#
# STEP 5: Copy Credentials
#   - Copy the "Client ID" and "Client secret"
#   - Paste them below
#
# STEP 6: Update Settings
#   - Set GOOGLE_OAUTH2_CLIENT_ID to your Client ID
#   - Set GOOGLE_OAUTH2_CLIENT_SECRET to your Client secret
#   - Set GOOGLE_OAUTH2_REDIRECT_URI to match your redirect URI
#
# STEP 7: Test
#   - Restart your Django server
#   - Try logging in with Google
# ============================================================================

# Google OAuth2 credentials (set these in environment variables for production)
GOOGLE_OAUTH2_CLIENT_ID = os.environ.get('GOOGLE_OAUTH2_CLIENT_ID', '')
GOOGLE_OAUTH2_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH2_CLIENT_SECRET', '')
GOOGLE_OAUTH2_REDIRECT_URI = os.environ.get(
    'GOOGLE_OAUTH2_REDIRECT_URI', 
    'http://127.0.0.1:8000/account/social/google/callback/'
)